Cherry pick of 39c7f3ff36910396926a8b02e26f6accbba08ffd failed
stdout:
Auto-merging personalizations_cotesma/models/stock_request_order.py
CONFLICT (content): Merge conflict in personalizations_cotesma/models/stock_request_order.py

stderr:
15:20:48.572041 git.c:439               trace: built-in: git cherry-pick 39c7f3ff36910396926a8b02e26f6accbba08ffd
error: could not apply 39c7f3f... [FIX] personalizations_cotesma: Add api depends.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes ingadhoc/personalizations#413

Signed-off-by: Pablo Paez Sheridan <pp@adhoc.com.ar>
Signed-off-by: Nicolas Mac Rouillon <nmr@adhoc.com.ar>