Cherry pick of 01f1e27eb797cb8bf2298add3a6a642fa1ade321 failed
stdout:
Auto-merging personalizations_cotesma/models/__init__.py
Auto-merging personalizations_cotesma/__manifest__.py
CONFLICT (content): Merge conflict in personalizations_cotesma/__manifest__.py

stderr:
10:03:59.159612 git.c:439               trace: built-in: git cherry-pick 01f1e27eb797cb8bf2298add3a6a642fa1ade321
error: could not apply 01f1e27... [IMP] cotesma: add search icon on request stock
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes ingadhoc/personalizations#480

Signed-off-by: Matias Peralta <mnp@adhoc.com.ar>
Signed-off-by: Bruno Zanotti <bz@adhoc.com.ar>