Cherry pick of a624182f0e075f01b2226225fc14be576eedeb7a failed
stdout:
Auto-merging personalizations_jureclaplata/models/__init__.py
CONFLICT (content): Merge conflict in personalizations_jureclaplata/models/__init__.py

stderr:
20:40:45.143502 git.c:439               trace: built-in: git cherry-pick a624182f0e075f01b2226225fc14be576eedeb7a
error: could not apply a624182... [REF] jureclaplata: clean up code
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes ingadhoc/personalizations#668

Signed-off-by: Katherine Zaoral <kz@adhoc.com.ar>